# 基础设置
sample_frequency: &sample_frequency
  30
go_on_path: ""
record_prefix_path: "data"
image_show: false
elapsed_time_show: false
robot_init_pos: &robot_init_pos
  [ 0.036, 0.639, 0.361, -174.882, -0.967, 4.658 ]
camera_names: &camera_names 
  ["camera0", "camera1", "camera2"]
robot_end_pos: [ -0.254, 0.628, 0.179, -171.285, -0.955 , 2.454 ]
end_delay: 10
# 机械臂客户端
robot_client:
  robot_init_pos: *robot_init_pos
  pos_target_d: 0.0025
  saved_mode: "hdf5"   # 保存模式： json zarr hdf5 
  prefix: "demo"
  camera_names: *camera_names
# XBOX
xbox_controller:
  sample_frequency: *sample_frequency
# 相机
cameras_subscriber:
  camera0:
    camera_id: 0
    if_record: false
    sample_frequency: *sample_frequency
    prefix: "videos"
  camera1:
    camera_id: 1
    if_record: false
    sample_frequency: *sample_frequency
    prefix: "videos"
  camera2:
    camera_id: 2
    if_record: false
    sample_frequency: *sample_frequency
    prefix: "videos"




