# 基础设置
sample_frequency: &sample_frequency 30
go_on_path: ""
record_prefix_path: "data"
image_show: false
elapsed_time_show: false
robot_init_pos: &robot_init_pos [ 0.093, 0.336, 0.341, -172.385, -1.685, 0 ]
robot_end_pos: [ -0.254, 0.628, 0.179, -171, -0.955, 2.454 ]
# camera_names: &camera_names ["cam_eye", "cam_right", "cam_left"]
camera_names: &camera_names ["cam_eye"]
saved_mode: &saved_mode "dp3" # 保存模式： json act dp3 
end_delay: 10
# 机械臂客户端
robot_client:
  robot_init_pos: *robot_init_pos
  pos_target_d: 0.003
  saved_mode: *saved_mode  
  prefix: "demo"
  camera_names: *camera_names
# XBOX
xbox_controller:
  sample_frequency: 50


