import pyRobotiqGripper
gripper = pyRobotiqGripper.RobotiqGripper("/dev/ttyUSB0")
gripper.activate()
gripper.calibrate(0, 40)
gripper.open()
position_in_bit = gripper.getPosition()
print(position_in_bit)
position_in_mm = gripper.getPositionmm()
print(position_in_mm)
gripper.close()
position_in_bit = gripper.getPosition()
print(position_in_bit)
position_in_mm = gripper.getPositionmm()
print(position_in_mm)
# gripper.goTo(100)
# position_in_bit = gripper.getPosition()
# print(position_in_bit)
# gripper.goTomm(25)
# position_in_mm = gripper.getPositionmm()
# print(position_in_mm)
# gripper.printInfo()